### ISSUE TITLE
Provide TypeScript definitions

### ISSUE THREAD

**Issue by LeoDanielsson** [DefinedNet/postcss-assign-layer#3]
This package lacks TypeScript definitions, which is a problem for projects with typed build configuration, such as Vite.

**Comment by IanVS** [comment]
Thanks @LeoDanielsson.  I've cleaned up the package a bit, converted it to TypeScript, and now dual-publish ESM and CJS along with types for each.  Try out the latest 0.3.0 version and let me know if you hit any issues.
